/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 25-Sep-2018 16:12:50
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 244
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#ifndef BANDPASS_H
#define BANDPASS_H
#include <stdint.h>
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define BPL  244
int16_t BP[] = {
        2,     -2,     -4,     -5,     -4,      0,      7,     12,     12,
        6,     -6,    -18,    -24,    -19,     -2,     19,     34,     35,
       18,    -10,    -35,    -46,    -35,     -8,     23,     42,     41,
       22,     -4,    -23,    -27,    -17,     -4,      0,     -7,    -17,
      -17,      4,     40,     72,     75,     34,    -42,   -119,   -152,
     -114,     -8,    122,    210,    207,    102,    -63,   -210,   -266,
     -200,    -39,    140,    252,    244,    127,    -36,   -163,   -199,
     -140,    -35,     53,     81,     53,     10,      0,     38,     97,
      119,     61,    -72,   -220,   -291,   -222,    -19,    230,    399,
      390,    191,   -109,   -364,   -448,   -324,    -62,    199,    332,
      291,    132,    -28,    -94,    -52,     25,     29,    -94,   -292,
     -419,   -325,     33,    527,    897,    885,    390,   -432,  -1204,
    -1508,  -1102,    -86,   1108,   1901,   1856,    914,   -538,  -1832,
    -2334,  -1765,   -355,   1255,   2309,   2309,   1255,   -355,  -1765,
    -2334,  -1832,   -538,    914,   1856,   1901,   1108,    -86,  -1102,
    -1508,  -1204,   -432,    390,    885,    897,    527,     33,   -325,
     -419,   -292,    -94,     29,     25,    -52,    -94,    -28,    132,
      291,    332,    199,    -62,   -324,   -448,   -364,   -109,    191,
      390,    399,    230,    -19,   -222,   -291,   -220,    -72,     61,
      119,     97,     38,      0,     10,     53,     81,     53,    -35,
     -140,   -199,   -163,    -36,    127,    244,    252,    140,    -39,
     -200,   -266,   -210,    -63,    102,    207,    210,    122,     -8,
     -114,   -152,   -119,    -42,     34,     75,     72,     40,      4,
      -17,    -17,     -7,      0,     -4,    -17,    -27,    -23,     -4,
       22,     41,     42,     23,     -8,    -35,    -46,    -35,    -10,
       18,     35,     34,     19,     -2,    -19,    -24,    -18,     -6,
        6,     12,     12,      7,      0,     -4,     -5,     -4,     -2,
        2
};
#endif
