/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 10-Dec-2018 16:08:21
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 245
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#ifndef HIGHPASS_H
#define HIGHPASS_H
#include <stdint.h>
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define HPL 244
int16_t HP[] = {
      375,      0,     -1,     -3,     -5,     -8,    -12,    -16,    -21,
      -26,    -31,    -36,    -41,    -46,    -51,    -55,    -59,    -62,
      -64,    -65,    -66,    -65,    -64,    -61,    -57,    -52,    -46,
      -39,    -31,    -22,    -13,     -3,      8,     18,     29,     39,
       49,     58,     66,     73,     79,     84,     87,     88,     88,
       86,     82,     76,     68,     58,     47,     34,     20,      5,
      -11,    -27,    -44,    -61,    -77,    -93,   -108,   -121,   -133,
     -142,   -149,   -154,   -156,   -155,   -151,   -143,   -133,   -119,
     -102,    -83,    -61,    -36,     -9,     19,     49,     79,    109,
      139,    168,    195,    221,    243,    262,    277,    288,    293,
      293,    287,    275,    257,    232,    201,    162,    117,     66,
        9,    -54,   -122,   -195,   -272,   -352,   -435,   -520,   -606,
     -692,   -777,   -860,   -941,  -1018,  -1091,  -1158,  -1220,  -1275,
    -1322,  -1362,  -1393,  -1416,  -1430,  31334,  -1430,  -1416,  -1393,
    -1362,  -1322,  -1275,  -1220,  -1158,  -1091,  -1018,   -941,   -860,
     -777,   -692,   -606,   -520,   -435,   -352,   -272,   -195,   -122,
      -54,      9,     66,    117,    162,    201,    232,    257,    275,
      287,    293,    293,    288,    277,    262,    243,    221,    195,
      168,    139,    109,     79,     49,     19,     -9,    -36,    -61,
      -83,   -102,   -119,   -133,   -143,   -151,   -155,   -156,   -154,
     -149,   -142,   -133,   -121,   -108,    -93,    -77,    -61,    -44,
      -27,    -11,      5,     20,     34,     47,     58,     68,     76,
       82,     86,     88,     88,     87,     84,     79,     73,     66,
       58,     49,     39,     29,     18,      8,     -3,    -13,    -22,
      -31,    -39,    -46,    -52,    -57,    -61,    -64,    -65,    -66,
      -65,    -64,    -62,    -59,    -55,    -51,    -46,    -41,    -36,
      -31,    -26,    -21,    -16,    -12,     -8,     -5,     -3,     -1,
        0,    375
};
#endif
