/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
 * Generated on: 15-Sep-2018 01:38:27
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 61
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#ifndef LOW_PASS_H
#define LOW_PASS_H
#include <stdint.h>
/*
 * Expected path to tmwtypes.h
 * G:\Matlab R2016b\extern\include\tmwtypes.h
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define LPL 61
int16_t LP[] = {
    -3715,     43,     55,     75,    102,    137,    179,    227,    282,
      342,    407,    477,    550,    627,    705,    784,    863,    942,
     1020,   1095,   1171,   1236,   1299,   1357,   1408,   1453,   1490,
     1520,   1541,   1554,   1559,   1554,   1541,   1520,   1490,   1453,
     1408,   1357,   1299,   1236,   1171,   1095,   1020,    942,    863,
      784,    705,    627,    550,    477,    407,    342,    282,    227,
      179,    137,    102,     75,     55,     43,  -3715
};
#endif
