/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 25-Sep-2018 15:54:51
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 244
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#ifndef LOWPASS_H
#define LOWPASS_H
#include <stdint.h>
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
#define LPL 244
int16_t LP[] = {
		-3,     -4,     -5,     -7,     -9,    -10,    -12,    -13,    -13,
		      -12,    -10,     -6,      0,      7,     16,     27,     40,     53,
		       67,     81,     94,    105,    114,    120,    122,    120,    114,
		      104,     89,     71,     51,     28,      6,    -16,    -36,    -53,
		      -65,    -71,    -72,    -67,    -57,    -41,    -21,      1,     24,
		       46,     66,     81,     91,     94,     90,     79,     61,     37,
		        9,    -21,    -50,    -78,   -100,   -115,   -123,   -120,   -108,
		      -87,    -57,    -21,     18,     58,     96,    128,    152,    165,
		      165,    152,    126,     88,     41,    -13,    -68,   -122,   -170,
		     -206,   -229,   -234,   -221,   -188,   -138,    -74,      2,     83,
		      163,    236,    296,    336,    352,    340,    300,    230,    135,
		       20,   -109,   -242,   -370,   -482,   -567,   -615,   -618,   -569,
		     -464,   -301,    -84,    184,    492,    831,   1187,   1546,   1891,
		     2207,   2480,   2697,   2848,   2925,   2925,   2848,   2697,   2480,
		     2207,   1891,   1546,   1187,    831,    492,    184,    -84,   -301,
		     -464,   -569,   -618,   -615,   -567,   -482,   -370,   -242,   -109,
		       20,    135,    230,    300,    340,    352,    336,    296,    236,
		      163,     83,      2,    -74,   -138,   -188,   -221,   -234,   -229,
		     -206,   -170,   -122,    -68,    -13,     41,     88,    126,    152,
		      165,    165,    152,    128,     96,     58,     18,    -21,    -57,
		      -87,   -108,   -120,   -123,   -115,   -100,    -78,    -50,    -21,
		        9,     37,     61,     79,     90,     94,     91,     81,     66,
		       46,     24,      1,    -21,    -41,    -57,    -67,    -72,    -71,
		      -65,    -53,    -36,    -16,      6,     28,     51,     71,     89,
		      104,    114,    120,    122,    120,    114,    105,     94,     81,
		       67,     53,     40,     27,     16,      7,      0,     -6,    -10,
		      -12,    -13,    -13,    -12,    -10,     -9,     -7,     -5,     -4,
		       -3
};
#endif
